# Generated by Django 3.1.2 on 2020-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('id_minat', models.IntegerField()),
                ('student_class', models.IntegerField()),
                ('score_math', models.IntegerField()),
                ('score_science', models.IntegerField()),
                ('score_indonesian', models.IntegerField()),
                ('cluster', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
